'use strict';
(async()=>{
 const $=s=>document.querySelector(s);let model,renderer;
 const categories={frame:'차체 · 상판',adapters:'높이 보정 · 연결대',drive:'후륜 구동 · 전륜 캐스터',battery:'납축전지 · 트레이',power:'전력 · 보호 소자',controls:'Raspberry Pi · 제어부',sensors:'라이다 · UWB',handle:'손잡이 · 비상정지',hardware:'부싱 · 케이블 고정',covers:'보호 커버',wires:'전원 · 신호 배선',accessories:'사용자 태그 · 외장 충전기'};
 const krnotes={
  'CART-DECK':'상판 900×600mm는 V8 구매 옵션이다. 상판 높이 310mm, 두께 18mm, 프레임 단면은 하부 배터리 배치를 위한 설계 제안이며 실측값이 아니다.',
  'BAT1':'왼쪽 하부에 세워 배치한 12V 납축전지이다. V8의 181×77×167mm를 적용했다. 트레이, 절연 패드, 단자 보호대와 고정 밴드를 포함한다.',
  'BAT2':'오른쪽 하부에 세워 배치한 12V 납축전지이다. BAT1과 직렬로 연결한다. 두 배터리의 플러스 단자 가까이에 각각 퓨즈가 있다.',
  'PI4':'Raspberry Pi 4B 8GB로 변경했다. PCB 85×56mm와 별도로 RBP-002 케이스 100×75×35mm의 임시 공간을 적용했다. 듀얼팬 외관과 포트 위치는 실측 대상이다.',
  'SCMB-L':'Motor-Bracket Rev A의 원래 솔리드를 Z축으로 180° 회전해 적용했다. 반대편과 동일한 가공품이며 장착홀을 거울상으로 바꾸지 않았다. 88mm 축-상면 높이를 유지한다.',
  'SCMB-R':'Motor-Bracket Rev A의 원래 솔리드와 4개 비대칭 홀 좌표를 유지했다. 높이 연결대는 브라켓과 별도 부품이다. 하중·축 지지력·실물 체결 검증은 남아 있다.',
  'MOTOR-L':'V8 기준 Ø72 몸통을 적용했다. Motor-Bracket 참고 외형 Ø102와 충돌하는 값이므로 미확정으로 표시한다. 기어박스 윤곽과 출력축 어깨 위치는 실측 대상이다.',
  'MOTOR-R':'24V 250W MY1016Z이다. 180rpm 구매 옵션을 유지하되 속도·감속비·몸통 외형은 입고품을 확인해야 한다. 회전 방향은 실제 배선 시험으로 결정한다.',
  'E-STOP':'손잡이의 래칭형 비상정지 버튼이다. NC 접점이 K1 코일 회로를 끊는 배치이며 복귀 후에는 별도 RESET 버튼이 필요하다. 전원 차단을 즉시 제동으로 간주하지 않는다.',
  'RESET':'비상정지 해제 후 K1 보조접점의 자기유지 회로를 수동으로 시작하는 순간 동작 버튼이다. 소프트웨어 자동 재시작을 전제로 하지 않는다.',
  'LIDAR':'RPLIDAR C1 공식 외형 55.6×55.6×41.3mm, 43×43mm 체결 간격과 스캔 높이 +29.8mm를 반영했다. 적재물은 후방 스캔을 가릴 수 있다. 360° 시야가 보장된 배치가 아니다.',
  'INA226':'INA226은 전압 감시용 배치로 남기고 고전류 입력 패드는 OPEN이다. V8의 R010 20A 판매 표기를 모터 합산 전류 허용치로 사용하지 않는다. 구매 모듈의 VBUS 접근 핀 확인이 필요하다.',
  'J-SERVICE':'정비용 전원 커넥터를 분리한 상태이다. 커넥터 틈을 가로지르는 가짜 배선은 없다. 개별 12V 충전 시 두 배터리와 직렬 링크를 모두 분리하고 충전기 절연 조건을 확인해야 한다.',
  'USB-HUB':'센서 전류를 Pi USB에 모두 의존하지 않도록 외부전원 허브를 추가한 설계이다. 실제 허브의 역급전 방지와 출력 전류를 확인해야 한다.',
  'DC5':'24V 계통에서 Pi·USB 허브에 5.1V를 공급하는 별도 DC/DC 공간이다. 6A 이상 전원 예산을 제안하지만 실제 모델, 리플, 방열 및 입력 상한은 미선정이다.',
  'K1':'전력 차단용 DC 접촉기의 위치를 확보했다. 실제 DC 차단 정격과 코일·보조접점을 선정해야 한다. 하우징은 특정 구매품의 확정 도면이 아니다.'
 };
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 try{
   let r=await fetch('data/assembly.json');if(!r.ok)throw Error('assembly.json HTTP '+r.status);model=await r.json();$('#load-detail').textContent='정확한 솔리드 메시를 읽습니다. 첫 실행은 파일 크기에 따라 잠시 걸릴 수 있습니다.';
   r=await fetch('data/geometry.bin');if(!r.ok)throw Error('geometry.bin HTTP '+r.status);const bytes=await r.arrayBuffer();try{renderer=new D5Renderer.Renderer($('#scene'),model,bytes);renderer.backend='WebGL 2'}catch(gpuError){const old=$('#scene'),replacement=old.cloneNode();old.replaceWith(replacement);renderer=new D5CPU.Renderer(replacement,model,bytes);renderer.fallbackReason=gpuError.message}window.D5={model,renderer};
   $('#loader').hidden=true;$('#component-count').textContent=model.counts.components+'개 참조 · '+model.counts.connections+'개 케이블';
   const defaultsOpen=['drive','battery','controls'];
   function tree(){const query=$('#search').value.trim().toLowerCase();$('#tree').replaceChildren();for(const [cat,title] of Object.entries(categories)){const cs=model.components.filter(c=>c.category===cat&&(!query||(c.id+' '+c.name+' '+(krnotes[c.id]||'')).toLowerCase().includes(query)));if(!cs.length)continue;const d=document.createElement('details');d.open=query?true:defaultsOpen.includes(cat);d.innerHTML='<summary>'+esc(title)+' <span>'+cs.length+'</span></summary>';for(const c of cs){const b=document.createElement('button');b.className='part'+(renderer.state.selection===c.id?' active':'');b.dataset.ref=c.id;b.innerHTML='<span class="dot"></span><span>'+esc(c.name)+'<b>'+esc(c.id)+'</b></span>';b.onclick=()=>{select(c.id);if(cat==='accessories'){renderer.state.accessories=true;$('#opt-accessories').checked=true;renderer.change()}if(innerWidth<761)$('#sidebar').classList.remove('open')};d.append(b)}$('#tree').append(d)}}
   function select(ref){renderer.state.selection=ref;renderer.invalid=true;document.querySelectorAll('.part').forEach(b=>b.classList.toggle('active',b.dataset.ref===ref));if(!ref){$('#inspector').hidden=true;return}const c=model.components.find(c=>c.id===ref);if(!c)return;$('#inspector').hidden=false;$('#inspect-id').textContent=ref;$('#inspect-name').textContent=c.name;$('#inspect-grade').textContent=c.grade;const w=model.connections.find(w=>w.id===ref);$('#inspect-note').textContent=krnotes[ref]||c.note||'입고품 형상과 장착 위치를 확인해야 하는 조립 요소이다. 자세한 기준은 치수 문서를 확인한다.';if(w){$('#inspect-data').innerHTML='<div class="inspect-grid"><span>시작<b>'+esc(w.from)+'</b></span><span>도착<b>'+esc(w.to)+'</b></span><span>중심선 길이<b>'+w.length_mm+' mm</b></span><span>가절단 제안 +15%<b>'+w.cut_length_proposal_mm+' mm</b></span><span>외경<b>Ø'+w.od_mm+' mm</b></span><span>최소 모델 굴곡반경<b>'+Number(w.bend_min_mm).toFixed(1)+' mm</b></span></div>'}else{const gs=model.geometry.filter(g=>g.ref===ref);const lo=[0,1,2].map(i=>Math.min(...gs.map(g=>g.bbox_mm[i]))),hi=[0,1,2].map(i=>Math.max(...gs.map(g=>g.bbox_mm[i+3])));$('#inspect-data').innerHTML='<div class="inspect-grid"><span>현재 모델 외곽<b>'+hi.map((x,i)=>(x-lo[i]).toFixed(1)).join(' × ')+' mm</b></span><span>분류<b>'+esc(categories[c.category])+'</b></span></div>'}}
   renderer.onpick=select;renderer.onhome=()=>view('overall');renderer.onerror=e=>{showError(e)};$('#close-inspector').onclick=()=>select('');$('#focus').onclick=()=>renderer.focus(renderer.state.selection);$('#search').oninput=tree;tree();
   const views={overall:{yaw:-.86,pitch:.47,distance:2.16,target:[-.015,0,.46],deck:true,title:'Smart-Cart-5 · 프로토타입 조립 상태',sub:'900 × 600 mm · 하부 좌우 납축전지 · Raspberry Pi 4B'},underside:{yaw:-.80,pitch:-.78,distance:1.48,target:[0,0,.19],deck:true,title:'가려지지 않는 하부.',sub:'배터리 트레이 · 중앙 전력부 · 실제 브라켓 · 전용 연결대'},drive:{yaw:-2.05,pitch:.14,distance:.82,target:[-.32,-.24,.17],deck:true,title:'후륜 구동과 하중 경로.',sub:'동일한 SCMB 두 개 · 하중 분산판 · 별도 높이 연결대'},power:{yaw:-.42,pitch:1.12,distance:1.03,target:[-.035,0,.225],deck:false,title:'전력부는 배터리 사이에.',sub:'커버·상판 제외 · 퓨즈·차단기·분배 단자 · 모터선 분리'},controls:{yaw:-.64,pitch:1.05,distance:.69,target:[-.30,0,.345],deck:true,title:'Pi 4B 중심의 제어부.',sub:'듀얼팬 케이스 · 외부전원 USB 허브 · ESP32 · INA226'},front:{yaw:0,pitch:.02,distance:1.82,target:[-.02,0,.45],deck:true,title:'전방 센서와 차체 폭.',sub:'C1 전방 돌출 배치 · 좌우 BU04 · 자유회전 전륜'},top:{yaw:-Math.PI/2,pitch:1.56,distance:1.65,target:[0,0,.37],deck:true,title:'900 × 600, 적재 공간 유지.',sub:'프레임 새로 제작 대신 기존 플랫폼 + 국부 연결대'}};
   function view(key){Object.assign(renderer.state,views[key],{covers:false});for(const k of ['deck','covers'])$('#opt-'+k).checked=renderer.state[k];$('#view-title').innerHTML=views[key].title;$('#view-sub').textContent=views[key].sub;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===key));select('');renderer.change();window.D5.currentView=key}
   window.D5.setView=view;window.D5.select=select;
   document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));for(const k of ['deck','covers','wires','floor','labels','accessories'])$('#opt-'+k).onchange=e=>{renderer.state[k]=e.target.checked;renderer.change()};
   $('#menu').onclick=()=>$('#sidebar').classList.toggle('open');
   const anns=[['E-STOP','손잡이 비상정지',[-480,160,975]],['LIDAR','RPLIDAR C1',[482,0,385]],['BAT1','납축전지 L',[-40,225,185]],['BAT2','납축전지 R',[-40,-225,185]],['PI4','Pi 4B 8GB',[-318,-85,367]]];
   renderer.onframe=()=>{$('#ground-state').textContent=renderer.groundVisible()?'드래그 회전 · 우클릭 이동 · 휠 확대 · 더블클릭 부품 확대':'하부 관찰 모드 · 바닥 자동 숨김 · 위로 회전하면 복원';$('#render-state').textContent=renderer.backend+' · '+model.counts.triangles.toLocaleString()+' triangles'+(renderer.fallbackReason?' · 호환 렌더링':'');$('#anchors').replaceChildren();if(renderer.state.labels)for(const [ref,title,p] of anns){const pos=renderer.project(p);if(!pos)continue;const e=document.createElement('span');e.className='anchor';e.textContent=title;e.style.left=pos[0]+'px';e.style.top=pos[1]+'px';$('#anchors').append(e)}};
   $('#snapshot').onclick=()=>{renderer.draw();$('#scene').toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Smart-Cart-5-'+(window.D5.currentView||'view')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')};
   const q=new URLSearchParams(location.search);if(q.has('view')&&views[q.get('view')])view(q.get('view'));else view('overall');if(q.has('part'))select(q.get('part'));
 }catch(e){showError(e.message||String(e));console.error(e)}
 function showError(message){$('#loader').hidden=false;$('#loader .spinner').hidden=true;$('#loader strong').textContent='모델을 불러오지 못했습니다.';$('#load-detail').textContent=message+' · ZIP을 완전히 풀고 start-local.bat 또는 python -m http.server 8000으로 실행하세요. file:// 실행은 지원하지 않습니다.'}
})();
